### ISSUE TITLE
/whereis

### ISSUE THREAD

**Issue by nthirtyone** [nthirtyone/avorion-scripts#9]
On branch `new-commands`.

Hardly an issue, just using it for discussion.

I have noticed that [player/cmd/tellposition.lua](https://github.com/AvorionCommands/avorion-scripts/blob/new-commands/scripts/player/cmd/tellposition.lua) and [player/cmd/whereis.lua](https://github.com/AvorionCommands/avorion-scripts/blob/new-commands/scripts/player/cmd/whereis.lua) are very similar. They could be easily merged into a single script for `wantedPlayer` (like `tellposition` currently). Is there any particular reason for them being split?

**Comment by mark-kubacki** [comment]
One is run in the context of the requestor, the other in the context of the wanted player (who, obviously, won't respond with the current location if offline).

**Comment by nthirtyone** [comment]
Right, Player needs to be online in opposition to Faction. I was thinking about it from completely different point of view (from Faction - thinking that Player could be created when he/she is offline - it doesn't sound that stupid when you think of it, seriously).

But it still seems that at least [player/cmd/whereis.lua](https://github.com/AvorionCommands/avorion-scripts/blob/new-commands/scripts/player/cmd/whereis.lua) is not needed. You can get home sector of `wantedPlayer` and send message to `requestor` directly from the command's `execute()`, yes? I guess it is clearer this way. I should stop wasting your time on pointless discussions, heh.
